### ISSUE TITLE
Some files still can not be derived from the code base

### ISSUE THREAD

**Issue by TronYY** [huevosabio/cs341#2]
Dear authors, 

I found some files still can not be derived from the code base.

For example, LSTMPrediction.ipynb needs to load some files (e.g., 'ignored_assets/to_lstm_3b_3f.csv', 'ignored_assets/new_lstm_to_pred.csv') to generate different predictor for Matlab simulation part, I searched the whole cs341 code base but found nowhere to generate those files.

Now I can only use LSTMPrediction.ipynb to generate empty predictor, and simulate no prediction scenario.

I want to simulate with prediction part, could you please give me some advice?

(message to your stanford mail couldn't be delivered...)

**Comment by federico3** [comment]
The LSTM prediction is more up @huevosabio 's alley, and I hope he will be able to comment.

However, looking at the code, I strongly suspect that the predictions we used in the paper are actually the ones in [`GoodPrediction.ipynb`](https://github.com/huevosabio/cs341/blob/398f03ac295f6d64d583211c43ff24bbed9ba63e/GoodPrediction.ipynb), and not the ones in `LSTM_prediction.ipynb`.

The `GoodPrediction` notebook depends on two files, `trainPredict.npy` and `testPredict.npy`, which are generated by [`build_lstm.py`](https://github.com/huevosabio/cs341/blob/398f03ac295f6d64d583211c43ff24bbed9ba63e/build_lstm.py).

`build_lstm`, in turn, needs `X.npy` and `Y.npy`, which are generated by [`data_preprocess.ipynb`](https://github.com/huevosabio/cs341/blob/398f03ac295f6d64d583211c43ff24bbed9ba63e/data_preprocess.ipynb).

The notebook `LSTM_prediction` was a previous attempt at LSTM predictions by another coauthor - I am fairly sure we ended up not using them, but Ramon can confirm.

Thanks for the patience, and sorry you have to dig through our unorganized code!

Also, sorry about the Stanford email. My affiliation finally expired last summer.

**Comment by federico3** [comment]
Closed per communication in #3
